name: Library update check
on:
  push:
    branches: [ develop/* ]

jobs:
  nodejs-js-express:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src/nodejs-js-express
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install -g npm-check-updates
      - name: NPM update check
        run: ncu

  nodejs-ts-express:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src/nodejs-ts-express
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install -g npm-check-updates
      - name: NPM update check
        run: ncu
