name: Test all of them
on:
  push:
    branches: [ develop/* ]
  pull_request:
    branches: [ main ]

jobs:
  node_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: 1st_take/src/nodejs-js-express
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci
